wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: huggingface
    huggingface_version: 4.22.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.0
    start_time: 1661093903.632764
    t:
      1:
      - 11
      - 12
      - 45
      - 49
      - 55
      2:
      - 11
      - 12
      - 45
      - 49
      - 55
      3:
      - 23
      4: 3.8.0
      5: 0.13.1
      6: 4.22.0.dev0
      8:
      - 5
